require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LetterCampaignsController do

  # This should return the minimal set of attributes required to create a valid
  # LetterCampaign. As you add validations to LetterCampaign, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all letter_campaigns as @letter_campaigns" do
      letter_campaign = LetterCampaign.create! valid_attributes
      get :index
      assigns(:letter_campaigns).should eq([letter_campaign])
    end
  end

  describe "GET show" do
    it "assigns the requested letter_campaign as @letter_campaign" do
      letter_campaign = LetterCampaign.create! valid_attributes
      get :show, :id => letter_campaign.id.to_s
      assigns(:letter_campaign).should eq(letter_campaign)
    end
  end

  describe "GET new" do
    it "assigns a new letter_campaign as @letter_campaign" do
      get :new
      assigns(:letter_campaign).should be_a_new(LetterCampaign)
    end
  end

  describe "GET edit" do
    it "assigns the requested letter_campaign as @letter_campaign" do
      letter_campaign = LetterCampaign.create! valid_attributes
      get :edit, :id => letter_campaign.id.to_s
      assigns(:letter_campaign).should eq(letter_campaign)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LetterCampaign" do
        expect {
          post :create, :letter_campaign => valid_attributes
        }.to change(LetterCampaign, :count).by(1)
      end

      it "assigns a newly created letter_campaign as @letter_campaign" do
        post :create, :letter_campaign => valid_attributes
        assigns(:letter_campaign).should be_a(LetterCampaign)
        assigns(:letter_campaign).should be_persisted
      end

      it "redirects to the created letter_campaign" do
        post :create, :letter_campaign => valid_attributes
        response.should redirect_to(LetterCampaign.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved letter_campaign as @letter_campaign" do
        # Trigger the behavior that occurs when invalid params are submitted
        LetterCampaign.any_instance.stub(:save).and_return(false)
        post :create, :letter_campaign => {}
        assigns(:letter_campaign).should be_a_new(LetterCampaign)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LetterCampaign.any_instance.stub(:save).and_return(false)
        post :create, :letter_campaign => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested letter_campaign" do
        letter_campaign = LetterCampaign.create! valid_attributes
        # Assuming there are no other letter_campaigns in the database, this
        # specifies that the LetterCampaign created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LetterCampaign.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => letter_campaign.id, :letter_campaign => {'these' => 'params'}
      end

      it "assigns the requested letter_campaign as @letter_campaign" do
        letter_campaign = LetterCampaign.create! valid_attributes
        put :update, :id => letter_campaign.id, :letter_campaign => valid_attributes
        assigns(:letter_campaign).should eq(letter_campaign)
      end

      it "redirects to the letter_campaign" do
        letter_campaign = LetterCampaign.create! valid_attributes
        put :update, :id => letter_campaign.id, :letter_campaign => valid_attributes
        response.should redirect_to(letter_campaign)
      end
    end

    describe "with invalid params" do
      it "assigns the letter_campaign as @letter_campaign" do
        letter_campaign = LetterCampaign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LetterCampaign.any_instance.stub(:save).and_return(false)
        put :update, :id => letter_campaign.id.to_s, :letter_campaign => {}
        assigns(:letter_campaign).should eq(letter_campaign)
      end

      it "re-renders the 'edit' template" do
        letter_campaign = LetterCampaign.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LetterCampaign.any_instance.stub(:save).and_return(false)
        put :update, :id => letter_campaign.id.to_s, :letter_campaign => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested letter_campaign" do
      letter_campaign = LetterCampaign.create! valid_attributes
      expect {
        delete :destroy, :id => letter_campaign.id.to_s
      }.to change(LetterCampaign, :count).by(-1)
    end

    it "redirects to the letter_campaigns list" do
      letter_campaign = LetterCampaign.create! valid_attributes
      delete :destroy, :id => letter_campaign.id.to_s
      response.should redirect_to(letter_campaigns_url)
    end
  end

end
